### ISSUE TITLE
ATP sensor installation on teamed interfaces

### ISSUE THREAD

**Issue by cheapscotman** [MicrosoftDocs/ATADocs#282] opened 2020-02-05 19:29 UTC
The installation will not work on physical 2019 servers with teamed ports if you install the npcap sensor first and then the ATP sensor. Uninstall the npcap sensor if it is installed and then install the ATP sensor. ATP will complain about the teamed sensor. Uninstall the ATP sensor, install npcap sensor, then the ATP sensor again. There are file dependencies that are needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71a56ac5-d132-1427-4c55-12921ec978c7
* Version Independent ID: aad125e7-7fa3-5fec-e025-2da79e11f44a
* Content: [Troubleshooting Azure ATP known issues](https://docs.microsoft.com/en-us/azure-advanced-threat-protection/troubleshooting-atp-known-issues#feedback)
* Content Source: [ATPDocs/troubleshooting-atp-known-issues.md](https://github.com/Microsoft/ATADocs/blob/master/ATPDocs/troubleshooting-atp-known-issues.md)
* Service: **azure-advanced-threat-protection**
* GitHub Login: @shsagir
* Microsoft Alias: **shsagir**

**Comment by mlottner** [comment] 2020-02-16 15:43
@cheapscotman Thanks for taking the time to leave us your feedback. 
You wrote " The installation will not work on physical 2019 servers with teamed ports if you install the npcap sensor first and then the ATP sensor". After checking with both product and engineering teams, we cannot find any scenario this would not work or that ATP would provide errors about the teamed sensor. 
Did you contact the product or support teams about your specific instance or experience to try to understand the root cause? Installation on teamed interfaces should behave exactly as documented.

**Comment by mlottner** [comment] 2020-02-17 15:20
@cheapscotman I'm closing this issue for now, but feel free to continue to comment here with your findings. 
If you continue to have this issue, please reach out to support to find a resolution to this specific issue in your environment. 
#please-close

**Closed by mlottner** 2020-02-17 15:20 UTC
Labels: Pri2, azure-advanced-threat-protection/svc
