### ISSUE TITLE
Docs required for one-way trusted domains

### ISSUE THREAD

**Issue by alexhass** [MicrosoftDocs/ATADocs#642] opened 2023-07-06 14:10 UTC
We have a one-way-trust between two windows domains. The ATP sensor on the domain CONTOSO1 works fine. The sensor on CONTOSO2 domain tries to query CONTOSO1 domain permanently and logs errors that it cannot connect to LDAP.

I think this is a defect of the sensor software, but maybe there is a way to cirumvent this and it is not yet documented.

```
2023-07-06 10:49:45.6355 Error DirectoryServicesClient+<SearchInternalAsync>d__38 RunPeriodic <RegisterPeriodicTask>b__1 failed
Microsoft.Tri.Infrastructure.ExtendedException: LDAP search failed [DomainControllerDnsName=contoso2.local IsGlobalCatalog=False DistinguishedName= Scope=Base Filter= AttributeCount=20] ---> System.DirectoryServices.Protocols.DirectoryOperationException: An operation error occurred.
   at DirectoryResponse System.DirectoryServices.Protocols.LdapConnection.ConstructResponse(int messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeOut, bool exceptionOnTimeOut)
   at DirectoryResponse System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at async Task<IReadOnlyCollection<SearchResultEntry>> Microsoft.Tri.Sensor.DirectoryServicesClient.SearchInternalAsync(SearchRequest searchRequest, DomainControllerConnection domainControllerConnection, DirectoryServicesSearchOptions options)
   --- End of inner exception stack trace ---
   at async Task<IReadOnlyCollection<SearchResultEntry>> Microsoft.Tri.Sensor.DirectoryServicesClient.SearchInternalAsync(SearchRequest searchRequest, DomainControllerConnection domainControllerConnection, DirectoryServicesSearchOptions options)
   at async Task<IReadOnlyCollection<DirectoryServicesSearchResult>> Microsoft.Tri.Sensor.DirectoryServicesClient.SearchAsync(SearchRequest searchRequest, DomainControllerConnection domainControllerConnection, DirectoryServicesSearchOptions options)
   at async Task<IReadOnlyCollection<DirectoryServicesSearchResult>> Microsoft.Tri.Sensor.DirectoryServicesClient.SearchObjectsInternalSyncedAsync(DomainControllerConnection domainControllerConnection, DistinguishedName baseDistinguishedName, SearchScope scope, string filter, string[] attributeNames, DirectoryServicesSearchOptions options)
   at void Microsoft.Tri.Infrastructure.Syncer<T, TResult>+<>c__DisplayClass1_0+<<RunAsync>g__RunFunctionAsync|0>d.MoveNext()
   at async Task<DirectoryServicesSearchResult> Microsoft.Tri.Sensor.DirectoryServicesClient.SearchObjectInternalAsync(DomainControllerConnection domainControllerConnection, DistinguishedName baseDistinguishedName, SearchScope scope, string filter, string[] attributeNames, DirectoryServicesSearchOptions options)
   at async Task Microsoft.Tri.Sensor.DirectoryServicesClient.UpdateDomainControllerConnectionDataAsync(DomainControllerConnectionData domainControllerConnectionData)
   at async Task Microsoft.Tri.Sensor.DirectoryServicesClient.ReconnectDisconnectedDomainControllersAsync()+(?) => { }
   at async Task<IReadOnlyCollection<TItem>> Microsoft.Tri.Infrastructure.EnumerableExtension.WhereAsync<TItem>(IEnumerable<TItem> enumerable, Func<TItem, Task<bool>> predicateAsync)
   at async Task Microsoft.Tri.Sensor.DirectoryServicesClient.ReconnectDisconnectedDomainControllersAsync()
   at async Task Microsoft.Tri.Sensor.DirectoryServicesClient.TraverseDomainTrustsAsync()
   at async Task Microsoft.Tri.Infrastructure.Module.RunTaskAsync(Func<Task> actionAsync, string name, SimpleTimeMetric timeMetric)
   at void Microsoft.Tri.Infrastructure.Module+<>c__DisplayClass28_0+<<RegisterPeriodicTask>b__1>d.MoveNext()
   at void Microsoft.Tri.Infrastructure.TaskExtension+<>c__DisplayClass22_0+<<RunPeriodic>b__0>d.MoveNext()
```

Aside of this I have no idea how to file a bugcase for this. Maybe you can do this internally?

**Comment by batamig** [comment] 2023-08-01 12:02
Hi @alexhass,
Thanks for writing into docs! You'll need to open a support ticket to investigate your specific use case.
You can find information about support options in our docs here: [Microsoft Defender for Identity support](https://learn.microsoft.com/en-us/defender-for-identity/support)

I'm closing this issue for now, but feel free to continue commenting if you have specific feedback on our docs.
#please-close

**Comment by alexhass** [comment] 2023-08-01 17:08
Can you document how to disable requests to non-trusted domains, please?

**Comment by batamig** [comment] 2023-08-02 08:01
Hi @alexhass, I've opened a backlog item to investigate further. I'm also tagging an SME who might be able to help.
@martin77s - are you able to advise here?

**Comment by martin77s** [comment] 2023-08-08 09:46
Whenever the sensor sees traffic or events with entities from remote domains it will try to query that domain to resolve those entities. This is by design. 
Even though the remote domain is not trusted, it would be able to use a DSA (added in the portal) from that domain to authenticate and run the required LDAP query.
See https://learn.microsoft.com/defender-for-identity/directory-service-accounts#number-of-dsa-entries

**Comment by batamig** [comment] 2023-08-08 09:49
Thanks Martin!
@alexhass, please confirm if this answers your question.

**Comment by alexhass** [comment] 2023-08-13 13:04
Than you documentation has a problem again. I followed exactly your documentation, made suggestions to fix some unclear stuff in the documentation, that you took over.

But multidomain information does not exists in your documentation. I made exactly nothing for cross domain. The accounts are added to the defender portal. Both gMSA accounts are created the same way in both domains. The domain1.local can access the domains2.local without a single issue, but the domain2.local cannot access the domain1.local. Again, I only followed your documentation and powershell scripts have been executed on both domains the same way.

I thought it has something to do with trust relationship, but you say it has nothing to do with it. So my assumption this is related may be wrong, but I can only say - I do have this issue. domain2 cannot read domain1.

**Comment by batamig** [comment] 2023-08-15 14:13
Hi @alexhass, thanks for letting us know. 
Please open a support ticket for this issue so that our dedicated support team can dive in and understand the full scenario. They will of course come back to us with any suggestions for docs and we'll update it as needed. 
I'm going to close this issue now - thank you for your contributions!
#please-close

**Closed by batamig** 2023-08-15 14:13 UTC
Labels: Pri3, backlog-item-created, tagged-sme
